{
  "test_helper.py::TestHelper::()::test_populate": true,
  "test_helper.py::TestHelper::()::test_setup": true,
  "test_organization.py::TestOrganization::()::test_me_post": true,
  "test_user.py::TestUser::()::test_me_del": true,
  "test_user.py::TestUser::()::test_me_get": true,
  "test_user.py::TestUser::()::test_me_post": true,
  "test_user.py::TestUser::()::test_me_post_activate_user": true,
  "test_user.py::TestUser::()::test_me_put": true,
  "test_user.py::TestUserExceptions::()::test_me_del_deleted_user": true,
  "test_user.py::TestUserExceptions::()::test_me_del_invalid_login": true,
  "test_user.py::TestUserExceptions::()::test_me_del_no_data": true,
  "test_user.py::TestUserExceptions::()::test_me_del_no_login": true,
  "test_user.py::TestUserExceptions::()::test_me_get_deleted_user": true,
  "test_user.py::TestUserExceptions::()::test_me_get_invalid_login": true,
  "test_user.py::TestUserExceptions::()::test_me_get_no_data": true,
  "test_user.py::TestUserExceptions::()::test_me_get_no_login": true,
  "test_user.py::TestUserExceptions::()::test_me_post_invalid_login": true,
  "test_user.py::TestUserExceptions::()::test_me_post_no_login": true,
  "test_user.py::TestUserExceptions::()::test_me_post_user_already_exists": true,
  "test_user.py::TestUserExceptions::()::test_me_put_deleted_user": true,
  "test_user.py::TestUserExceptions::()::test_me_put_invalid_login": true,
  "test_user.py::TestUserExceptions::()::test_me_put_no_data": true,
  "test_user.py::TestUserExceptions::()::test_me_put_no_login": true,
  "test_user.py::TestUserOrganization::()::test_me_organizations_get": true,
  "test_user.py::TestUserOrganization::()::test_me_organizations_post": true,
  "test_user.py::TestUserOrganizationExceptions::()::test_me_organizations_get_invalid_login": true,
  "test_user.py::TestUserOrganizationExceptions::()::test_me_organizations_get_no_data": true,
  "test_user.py::TestUserOrganizationExceptions::()::test_me_organizations_get_no_login": true,
  "test_user.py::TestUserOrganizationExceptions::()::test_me_organizations_post_invalid_login": true,
  "test_user.py::TestUserOrganizationExceptions::()::test_me_organizations_post_no_login": true
}